version: "3"
services:
  vrprouting:
    image: pgrouting/vrprouting:13-3.1-3.2.0-main
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
volumes:
  db-data:
